name: Build and Test React Project

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      - name: test app
        run: npm run test

      - name: Build project
        id: build
        run: npm run build

  merge-dev-into-main:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ needs.build-and-test.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge dev into main
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const repo = context.repo
            const { data: pullRequest } = await github.pulls.create({
              ...repo,
              title: 'Merge dev into main',
              head: 'dev',
              base: 'main',
              maintainer_can_modify: false,
            })
            await github.pulls.merge({
              ...repo,
              pull_number: pullRequest.number,
            })
